version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8
    working_directory: ~/ricecooker

    steps:
      - checkout

      - run:
          name: Build and Test
          command: mvn clean install

      - run:
          name: Checkstyle
          command: mvn checkstyle:check

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - feature/java